name: dev-test-code

on:
  push:
    branches-ignore:
      - main
    paths-ignore:
      - "scripts/**"
      - "BlocksScreen/lib/ui/**"
      - "extras/**"
  pull_request:
    branches-ignore:
      - main
    paths-ignore:
      - "scripts/**"
      - "BlocksScreen/lib/ui/**"
      - "extras/**"
jobs:
  formatting-check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11.2"]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff
      - name: Linting & Analyzing code formatting with Ruff
        run: |
          ruff check --output-format=github --target-version=py311 --config=pyproject.toml
          ruff format --diff --target-version=py311 --config=pyproject.toml
        continue-on-error: true
  QA-check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11.2"]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint
      - name: QA code with pylint
        run: |
          echo "Linting files..."
          pylint -j$(nproc) --recursive=y --rcfile=tools/.pylintrc.dev .
        continue-on-error: true
  Unit-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11.2"]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-cov
      - name: Running Unit tests with pytest
        run: |
          if [ -d "tests/" ] && [ "$(ls -A tests/)" ]; then 
            pytest tests/'*.py' --doctest-modules --junitxml=junit/test-results.xml --cov=com --conv-report=xml --cov-report=html 
          else
            echo "No tests directory no need to proceed with tests"
          fi
