name: dev-test-code

on:
  push:
    branches-ignore:
      - main
    paths-ignore:
      - "scripts/**"
      - "BlocksScreen/lib/ui/**"
      - "extras/**"
  pull_request:
    branches-ignore:
      - main
    paths-ignore:
      - "scripts/**"
      - "BlocksScreen/lib/ui/**"
      - "extras/**"
jobs:
  ci-checks:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11.2"]
        test-type: [ruff, pylint, pytest]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"
      - name: Install dependencies
        run: |
          echo "Installing dependencies"
          python -m pip install --upgrade pip
          pip install scripts -r scripts/requirements-dev.txt

      - name: Run Test ${{ matrix.test-type }}
        run: |
          echo "Starting test runs"
          if [ "${{ matrix.test-type }}" == "ruff" ]; then 
            echo "Running Formatting Test"
            ruff check --output-format=github --target-version=py311 --config=pyproject.toml > ruff_output.txt
            ruff format --diff --target-version=py311 --config=pyproject.toml
          fi
          if [ "${{ matrix.test-type }}" == "pylint" ]; then
            echo "Running Code Test"
            pylint -j$(nproc) --recursive=y --rcfile=.pylintrc.dev . > pylint-output.txt
          fi

          if [ "${{ matrix.test-type }}" == "pytest" ]; then
            if [ -d "tests/" ] && [ "$(ls -A tests/)" ]; then 
              echo "Running Python unit tests"
              pytest tests/'*.py' --doctest-modules --junitxml=junit/test-results.xml --cov=com --conv-report=xml --cov-report=html 
            else
              echo "No tests directory no need to proceed with tests"
            fi
          fi
        continue-on-error: false

