name: stage-ci

on: 
  branches:
    - stage
  paths-ignore:
    - "scripts/**"
    - "BlocksScreen/lib/ui/**"
    - "extras/**"
  workflow_run:
    workflows: ["dev-test-code"]
    types:
      - completed
  jobs:
  ci-stage:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      
      - name: Run staging pipeline
        run: echo "Running staging integration tests..."